#server:
#  port: 8098

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
         
#spring:
#  application:
#    name: student-service  # current Service name to be used by the eureka server
    
#management:
#  security:
#    enabled: false    

#    logging:
#      level:
#        demo: DEBUG